version: '3.8'

services:
  bot:
    image: node:17-alpine
    volumes:
      - "./:/app"
    env_file:
      - .env
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    restart: always